### PR TITLE
Stop using old-style simd_shuffle

### LINKED ISSUE #541: pathfinder_simd failed to compile with nightly toolchain on Apple M1 MBP
$ cd pathfind/simd
$ cargo +nightly b

...

```
   Compiling pathfinder_simd v0.5.1 (/Users/mhfan/Devel/blend2d/resvg/lottie-rs/pathfinder/simd)
error: unrecognized platform-specific intrinsic function: `simd_shuffle2`
   --> simd/src/arm/mod.rs:887:5
    |
887 |     fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: unrecognized platform-specific intrinsic function: `simd_shuffle4`
   --> simd/src/arm/mod.rs:888:5
    |
888 |     fn simd_shuffle4<T, U>(x: T, y: T, idx: [u32; 4]) -> U;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `pathfinder_simd` (lib) due to 2 previous errors
```

image

### PR DESCRIPTION
**Pull request by mhfan**
fix #541

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by yisibl** [comment]
After upgrading to 0.5.3, I encountered a compile error, can you help me out?

```bash
error[E0432]: unresolved import `std::intrinsics::simd`
  --> C:\Users\runneradmin/.cargo\registry\src\index.crates.io-6f17d22bba15001f\pathfinder_simd-0.5.3\src\arm\mod.rs:13:22
   |
13 | use std::intrinsics::simd::*;
   |                      ^^^^ could not find `simd` in `intrinsics`
```

**Comment by jdm** [comment]
Please open a new issue about that error!
