### ISSUE TITLE
arm simd compilation is broken

### ISSUE THREAD

**Issue by jdm** [servo/pathfinder#294]
```
    /// Converts these packed floats to integers via rounding.
    #[inline]
    pub fn to_i32x4(self) -> I32x4 {
        unsafe { I32x4(round_v4f32(simd_cast(self.0))) }
    }
```
This yields:
```
error[E0308]: mismatched types
   --> C:\Users\image\pathfinder\simd\src\arm\mod.rs:335:24
    |
335 |         unsafe { I32x4(round_v4f32(simd_cast(self.0))) }
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::arch::aarch64::int32x4_t`, found struct `std::arch::aarch64::float32x4_t`
```

**Comment by jdm** [comment]
This is a regression from https://github.com/servo/pathfinder/commit/eb66459ef401576352de4d3e72cd64b588b7dfb3; it would be good to get this target building on CI to avoid this in future.
